### ISSUE TITLE
Cusrom Disqus.NET.DisqusEndpoints.ApiUrl

### ISSUE THREAD

**Issue by luodaoyi** [akaSybe/Disqus.NET#2]
`disqus.com` is blocked by GFW in China, we'll have to setup a reverse proxy to access it. It would be nice to be able to set the the property `ApiUrl` in Disqus.NET.DisqusEndpoints.

**Comment by luodaoyi** [comment]
so i have  a Pull requests
Please accept this
thank you!

[https://github.com/akaSybe/Disqus.NET/pull/3](https://github.com/akaSybe/Disqus.NET/pull/3)

**Comment by akaSybe** [comment]
thank you for the contribution!
