### ISSUE TITLE
Console Application Example?

### ISSUE THREAD

**Issue by WillStrohl** [akaSybe/Disqus.NET#4]
Do you have an example of how to use this in a console application?

**Comment by WillStrohl** [comment]
I figured this out eventually... It was a pain in the behind to figure out how to write this correctly in a console app with debugging due to it having only `async` methods.  :)

**Comment by akaSybe** [comment]
Sorry for late response. Feel free to reopen issue if you still have any questions.

**Comment by WillStrohl** [comment]
No more questions. It was just difficult to troubleshoot and debug without more code samples and with it only being `async`.  I'm all good now.  Thanks!  :)
